version: "3.3"

services:

  # https://hub.docker.com/_/mysql
  otel-provider1-db:
    image: "mysql:5.7"
    ports:
      - "3306:3306"
    restart: "always"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_USER: "provider1"
      MYSQL_PASSWORD: "p@ssw0rd"
      MYSQL_DATABASE: "provider1"
    volumes:
      - "./provider1/scripts/init-db.sql:/tmp/init-db.sql:Z"
    command: [
      "--default-authentication-plugin=mysql_native_password",
      "--init-file=/tmp/init-db.sql"
    ]

  # https://hub.docker.com/_/mysql
  otel-provider2-db:
    image: "mysql:5.7"
    ports:
      - "3307:3306"
    restart: "always"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_ROOT_USER: "root"
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_USER: "provider2"
      MYSQL_PASSWORD: "p@ssw0rd"
      MYSQL_DATABASE: "provider2"
    volumes:
      - "./provider2/scripts/init-db.sql:/tmp/init-db.sql:Z"
    command: [
      "--default-authentication-plugin=mysql_native_password",
      "--init-file=/tmp/init-db.sql"
    ]

  otel-provider1:
    image: "otel-provider1:latest"
    ports:
      - "8082:8080"
    volumes:
      - "./provider1/config/application.yml:/config/application.yml:Z"

  otel-provider2:
    image: "otel-provider2:latest"
    ports:
      - "8083:8080"
    volumes:
      - "./provider2/config/application.yml:/config/application.yml:Z"

  otel-api:
    image: "otel-api:latest"
    ports:
      - "8081:8080"
    volumes:
      - "./api/config/application.yml:/config/application.yml:Z"

  otel-ui:
    image: "otel-ui:latest"
    ports:
      - "8080:8080"
    volumes:
      - "./ui/config/application.yml:/config/application.yml:Z"

  # https://www.jaegertracing.io/docs/1.18/getting-started/
  #jaeger:
  #  image: "jaegertracing/all-in-one:latest"
  #  ports:
  #    - "16686:16686"

  # From https://github.com/signalfx/splunk-otel-collector/blob/main/examples/docker-compose/docker-compose.yml
  splunk-otel-collector:
    image: quay.io/signalfx/splunk-otel-collector:latest
    environment:
      SPLUNK_ACCESS_TOKEN: "Jwpf31CWtPi6qFhlm1acZA"
      SPLUNK_REALM: "us1"
    ports:
      - "13133:13133"
      - "14250:14250"
      - "14268:14268"
      - "4317:4317"
      - "6060:6060"
      - "7276:7276"
      - "8888:8888"
      - "9080:9080"
      - "9411:9411"
      - "9943:9943"
